# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17cdd373dbf0e7bc1068c42f018ef71cc538d8bdb08ab4d485a7059854bc5a643276b0f99f350491873927d031b9944c1945e94370447741a64aacc4dc4f244b

test:
  secret_key_base: cf5372d60cff57f3219bb20add96846dfa663891112ec818156acaefb149ae018be674594ea8b372ec043e8ddf4ba13162e398195919161a531a9925b80b1538

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
